data:
  image_dir : "/mnt/g/Authenta/data/authenta-remaskable-inpainting-detection/images"
  annotation_file : "/mnt/g/Authenta/data/authenta-remaskable-inpainting-detection/annotations/instances_val2017.json"
  mask_dir : "/mnt/g/Authenta/data/authenta-remaskable-inpainting-detection/masks"
  inpainted_dir : "/mnt/g/Authenta/data/authenta-remaskable-inpainting-detection/Inpainted"

mask_generation:
  min_mask_area : 1000
  max_images : 10
  seed : 42

inpainting_models:
  - name: sd15
    model_id: "runwayml/stable-diffusion-inpainting"
    pipeline_class: "StableDiffusionInpaintPipeline"
    output_dir: "assets/inpainted/sd15"

  - name: sd2
    model_id: "stabilityai/stable-diffusion-2-inpainting"
    pipeline_class: "StableDiffusionInpaintPipeline"
    output_dir: "assets/inpainted/sd2"

  - name: sdxl
    model_id: "diffusers/stable-diffusion-xl-1.0-inpainting-0.1"
    pipeline_class: "StableDiffusionXLInpaintPipeline"
    output_dir: "assets/inpainted/sdxl"
