data:
  image_dir : "/mnt/g/Authenta/data/authenta-remaskable-inpainting-detection/images"
  annotation_file : "/mnt/g/Authenta/data/authenta-remaskable-inpainting-detection/annotations/instances_val2017.json"
  mask_dir : "/mnt/g/Authenta/data/authenta-remaskable-inpainting-detection/masks"
  inpainted_dir : "/mnt/g/Authenta/data/authenta-remaskable-inpainting-detection/Inpainted"

mask_generation:
  min_mask_area : 1000
  max_images : 500
  seed : 42

inpainting_models:
  - name: sd15
    model_id: "runwayml/stable-diffusion-inpainting"
    pipeline_class: "StableDiffusionInpaintPipeline"
    output_dir: "assets/inpainted/sd15"

  - name: sd2
    model_id: "stabilityai/stable-diffusion-2-inpainting"
    pipeline_class: "StableDiffusionInpaintPipeline"
    output_dir: "assets/inpainted/sd2"

  - name: repaint
    model_id: "CompVis/repaint"
    pipeline_class: "RePaintPipeline"
    output_dir: "assets/inpainted/repaint"
